### PR TITLE
Brand styles update

### PR DESCRIPTION
**Pull request by MariaNono**
@Smokyish sorry, I forgot to write the description. 
Indeed a lot of content changed:
- We should favour and use SCSS that was not working before in order to make it work I had to change some of the setup and file structure. I could not eliminate all of the plain CSS because there are rules there I could not find in the SCSS files.
- But I did eliminate a lot of CSS that was made the same as the SCSS or that was not necessary
- I had to update the brand guidelines pages. I opted to only have a pdf download link instead of all the slides in one page as pngs.
- The brand assets had to be replaced
- I removed the header on the READ.ME
- Certain HTML/Mark-Up had to be changed in order to add new classes and change the elements organisation so that other layouts/alignments would be possible
- I removed the thumbnails from the announcements, made the links 'Read More ->'  instead of 'More'
- I removed unnecessary indentation in a few files

### CODE REVIEW

**Comment by andfletcher** [comment]
@compojoom added you for review

**Comment by andfletcher** [comment]
@Smokyish please review.

**Review by Smokyish — CHANGES_REQUESTED** [review]
PR is missing a description of what this is supposed to change, how and why.

There's over 180 files changed, why, seems like only a few would had been needed for the style updates. Makes this pretty impossible to review on the code side, the site looks mostly okay though.

I will not accept any changes to content in a "style" PR. All those changes need to be reverted.

Also has many `.DS_Store` files that have to be removed.

**Comment by MariaNono** [comment]
@Smokyish please review again

**Pull request merged**
